### ISSUE TITLE
Can't use /nbt me key = value

### ISSUE THREAD

**Issue by SkyBeastMC** [DPOH-VAR/PowerNBT#13]
I can't use /nbt me hi = true for exemple.
I only can do /nbt item hi = true.
Why can't I write on a nbt player file?

I tested this on 2 plugins version and 2 bukkit versions. (with Spigot and without.)

**Comment by DPOH-VAR** [comment]
online player can contain tag "hi"
use offline player file, it works:
![example](http://linkme.ufanet.ru/images/adf74ae2e943c60328f1121d02c0ef42.png)
but value will disappear after saving the player or world.

 you can use forgeData on forge server:
``` /nbt me forgeData.hi = true ```

or use a local file with the same name as player:
``` /nbt $DPOHVAR hi = true ``` 
./plugins/PowerNBT/nbt/DPOHVAR.nbt

**Comment by SkyBeastMC** [comment]
> or use a local file with the same name as player:
> /nbt $DPOHVAR hi = true 
> ./plugins/PowerNBT/nbt/DPOHVAR.nbt

That's what I am using now.

> online player can't contain tag "hi"
> use offline player file, it works:

Nope this tag will automaticly be deleted when relogging.

Thanks !
