### ISSUE TITLE
Tab autocomplete truncated !

### ISSUE THREAD

**Issue by GhostorTron** [DPOH-VAR/PowerNBT#14]
Hi

Great job for your plugin. He save time for admin job on my server to edit Commands block, when it require a color text modification.

But now when i use command block and the string test is big, i use the text like this : 
"/nbt Block command = [TAB]"

It made only 1 lign and trunc it with that "            ..."        (3 points).

Impossible to set the text !

Can you correct them ?

**Comment by GhostorTron** [comment]
ohh forget to mention : 

- server on spigot 1.8.3 but i think it come on minecraft client version, not server.

**Comment by DPOH-VAR** [comment]
You can see text by command:
```/nbt Block command full```

If you need to restore text with [TAB] more than 60 characters, edit config.yml (or create):
```yaml
limit:
    vertical: 10
    horizontal: 60
```

**Comment by GhostorTron** [comment]
Thx a lot.

**Comment by DPOH-VAR** [comment]
Use ```§``` instead of a ```&``` when editing the file

**Comment by GhostorTron** [comment]
Sorry, but it don't work

Ok let me explain what i want : 

I put a command block and write this : 

"
/summon ArmorStand ~ ~ ~ {NoGravity:true,Invisible:true,CustomNameVisible:true,CustomName:"Bienvenue sur le serveur Nitrado",Invulnerable:true}
"

After that i try to put the color so i write on minecraft : 
/nbt block Command < $test

A new test.nbt file is create and inside : 
"
[]   /summon ArmorStand ~ ~ ~ {NoGravity:true,Invisible:true,CustomNameVisible:true,CustomName:"Bienvenue sur le serveur Nitrado",Invulnerable:true}
"
I try to modify the text, save and type in minecraft : 

/nbt block Command > $test

And it is there where it said : PowerNBT : Wrong format !

What i do wrong ?

**Comment by DPOH-VAR** [comment]
Don't use a text editor for this.
Here's the nbt editors:
webNBT: https://irath96.github.io/webNBT/
other: http://minecraft.gamepedia.com/NBT_format#Software

**Comment by GhostorTron** [comment]
Ok, i try this and this is my result : 
If i save on NBT format => webNBT can edit (but with no name for the data, strange), i save, i upload and when i reaffect the value inside data : error java ...
If i save on NBT format => NBTExplorer => can not open file ?????
If i save on NBTZ format => webNBT is the same result above (the first line)
If i save on NBTZ format => NBTExplorer => It can open file (with correct name DATA = ...). I save, reupload. And work ok when i reaffect the value.

So I'll use NBTZ format file via FTP to open it with NBTExplorer.

Thx a lot for you patience and help. your plugin is very usefull for admin like us.

Bye
