### ISSUE TITLE
Maven repository 400 error

### ISSUE THREAD

**Issue by bowser123467** [DPOH-VAR/PowerNBT#17]
The maven repository doesn't work right now:
http://varscript.ru/artifactory/snapshots/me/dpohvar/powernbt/PowerNBT/0.8.1/PowerNBT-0.8.1.jar
returns a 400 error

**Comment by DPOH-VAR** [comment]
fixed: 
https://repo.varscript.ru/
https://repo.varscript.ru/release
https://repo.varscript.ru/snapshots
