### ISSUE TITLE
NullPointerException in utils.ReflectionUtils "public T get()" (Line 800)

### ISSUE THREAD

**Issue by egg82** [DPOH-VAR/PowerNBT#21]
A stack-trace was given to me by the user "Hexanite" regarding one of my plugins that relies on PowerNBT.

The hastebin is available [here](https://hastebin.com/pigutosavi.vbs) or the full stack-trace below.
I have found the class and line number [here](https://github.com/DPOH-VAR/PowerNBT/blob/master/src/main/java/me/dpohvar/powernbt/utils/ReflectionUtils.java#L800).
My implementation that lead to this error (including specific line number) is available [here](https://github.com/egg82/PluginLibrary/blob/master/src/ninja/egg82/plugin/reflection/nbt/PowerNBTHelper.java#L121).

`10.07 15:41:29 [Server] ERROR Could not pass event InventoryClickEvent to TrollCommandsPlusPlus v4.17.36
10.07 15:41:29 [Server] INFO org.bukkit.event.EventException: null
10.07 15:41:29 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.jar:git-Spigot-7228328-50b75cd]
10.07 15:41:29 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.jar:git-Spigot-7228328-50b75cd]
10.07 15:41:29 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot-1.12.jar:git-Spigot-7228328-50b75cd]
10.07 15:41:29 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot-1.12.jar:git-Spigot-7228328-50b75cd]
10.07 15:41:29 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1877) [spigot-1.12.jar:git-Spigot-7228328-50b75cd]
10.07 15:41:29 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) [spigot-1.12.jar:git-Spigot-7228328-50b75cd]
10.07 15:41:29 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) [spigot-1.12.jar:git-Spigot-7228328-50b75cd]
10.07 15:41:29 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.jar:git-Spigot-7228328-50b75cd]
10.07 15:41:29 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
10.07 15:41:29 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
10.07 15:41:29 [Server] INFO at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.jar:git-Spigot-7228328-50b75cd]
10.07 15:41:29 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot-1.12.jar:git-Spigot-7228328-50b75cd]
10.07 15:41:29 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot-1.12.jar:git-Spigot-7228328-50b75cd]
10.07 15:41:29 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.12.jar:git-Spigot-7228328-50b75cd]
10.07 15:41:29 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.12.jar:git-Spigot-7228328-50b75cd]
10.07 15:41:29 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
10.07 15:41:29 [Server] INFO Caused by: java.lang.RuntimeException: java.lang.NullPointerException
10.07 15:41:29 [Server] INFO at me.dpohvar.powernbt.utils.ReflectionUtils$RefField$RefExecutor.get(ReflectionUtils.java:800) ~[PowerNBT.jar:?]
10.07 15:41:29 [Server] INFO at me.dpohvar.powernbt.utils.ItemStackUtils.getTag(ItemStackUtils.java:86) ~[PowerNBT.jar:?]
10.07 15:41:29 [Server] INFO at me.dpohvar.powernbt.utils.ItemStackUtils.getTagCB(ItemStackUtils.java:186) ~[PowerNBT.jar:?]
10.07 15:41:29 [Server] INFO at me.dpohvar.powernbt.utils.ItemStackUtils.getTag(ItemStackUtils.java:139) ~[PowerNBT.jar:?]
10.07 15:41:29 [Server] INFO at me.dpohvar.powernbt.api.NBTManager.read(NBTManager.java:108) ~[PowerNBT.jar:?]
10.07 15:41:29 [Server] INFO at me.egg82.tcpp.lib.ninja.egg82.plugin.reflection.nbt.PowerNBTHelper.hasTag(PowerNBTHelper.java:121) ~[TrollCommandsPlusPlus-4.17.36.jar:?]
10.07 15:41:29 [Server] INFO at me.egg82.tcpp.events.inventory.inventoryClick.AttachCommandEventCommand.onExecute(AttachCommandEventCommand.java:121) ~[TrollCommandsPlusPlus-4.17.36.jar:?]
10.07 15:41:29 [Server] INFO at me.egg82.tcpp.lib.ninja.egg82.patterns.SynchronousCommand.start(SynchronousCommand.java:37) ~[TrollCommandsPlusPlus-4.17.36.jar:?]
10.07 15:41:29 [Server] INFO at me.egg82.tcpp.events.InventoryClickEventCommand.lambda$0(InventoryClickEventCommand.java:37) ~[TrollCommandsPlusPlus-4.17.36.jar:?]
10.07 15:41:29 [Server] INFO at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_121]
10.07 15:41:29 [Server] INFO at me.egg82.tcpp.events.InventoryClickEventCommand.onExecute(InventoryClickEventCommand.java:35) ~[TrollCommandsPlusPlus-4.17.36.jar:?]
10.07 15:41:29 [Server] INFO at me.egg82.tcpp.lib.ninja.egg82.patterns.SynchronousCommand.start(SynchronousCommand.java:37) ~[TrollCommandsPlusPlus-4.17.36.jar:?]
10.07 15:41:29 [Server] INFO at me.egg82.tcpp.lib.ninja.egg82.plugin.reflection.event.EventListener_1_11_2.onAnyEvent(EventListener_1_11_2.java:785) ~[TrollCommandsPlusPlus-4.17.36.jar:?]
10.07 15:41:29 [Server] INFO at me.egg82.tcpp.lib.ninja.egg82.plugin.reflection.event.EventListener_1_11_2.onInventoryClick(EventListener_1_11_2.java:374) ~[TrollCommandsPlusPlus-4.17.36.jar:?]
10.07 15:41:29 [Server] INFO at sun.reflect.GeneratedMethodAccessor673.invoke(Unknown Source) ~[?:?]
10.07 15:41:29 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
10.07 15:41:29 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
10.07 15:41:29 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.jar:git-Spigot-7228328-50b75cd]
10.07 15:41:29 [Server] INFO ... 15 more
10.07 15:41:29 [Server] INFO Caused by: java.lang.NullPointerException`

I would initially assume I simply passed a null value as an ItemStack, but as you can see in my code I check for that beforehand; this tells me something else is going on entirely.

I see two possible solutions:
1) [public T get()](https://github.com/DPOH-VAR/PowerNBT/blob/master/src/main/java/me/dpohvar/powernbt/utils/ReflectionUtils.java#L796) returns null on an exception and the containing code handles the null appropriately.
2) The containing code handles the exception thrown appropriately and simply returns null.

I personally am a fan of option 1 as it results in fewer sandboxes and thus more performance. It also fires a null object sooner resulting in less cluttered code. However there may be other alternatives that I'm not seeing.

**Comment by DPOH-VAR** [comment]
There may be only one cause of the error
[ItemStackUtils.java:L125](https://github.com/DPOH-VAR/PowerNBT/blob/2a0e69fa3816f80f79669f3345ee8a724df2923e/src/main/java/me/dpohvar/powernbt/utils/ItemStackUtils.java#L125)
``` java 
private Object getHandle(ItemStack cbItemStack){
    return itemHandle.of(cbItemStack).get();
}
```
`cbItemStack` is not `null` and instance of `{cb}.CraftItemStack`, but `cbItemStack.handle` is `null`

I have not seen such behavior before 
but I think that I can solve this problem.

**Comment by DPOH-VAR** [comment]
Try this version
http://repo.varscript.ru/snapshots/me/dpohvar/powernbt/PowerNBT/0.8.8.1-SNAPSHOT/
If problem is solved, I will include this fix into master.

**Comment by egg82** [comment]
Thanks, I'll let you know if I hear anything back from the server owner.

**Comment by egg82** [comment]
It looks like the fix you posted solved the issue and may be safe to merge into master. Thank you again.
