### ISSUE TITLE
Update for 1.13.1

### ISSUE THREAD

**Issue by tonydu51** [DPOH-VAR/PowerNBT#28]
on start all it's ok but we try to modify a value (to hand/entity/blocks...) that give us a message error said the value don't change we can't edit.
so can you update ?
thanks

**Comment by DPOH-VAR** [comment]
Spigot --rev 1.13.1
PowerNBT version 0.8.9.2
All works fine

Please attach your log file.

**Comment by tonydu51** [comment]
nothing in my log only in game:
![nbt](https://user-images.githubusercontent.com/32870592/46343132-11e00980-c63d-11e8-9b23-3c6944becbe3.jpg)

**Comment by AndreyVakhterovMB** [comment]
> If it is any help

Thank you! I will try to reproduce this error again

**Comment by jb-aero** [comment]
I have found the issue. findMethodByReturnType is finding the first method in NBTBase that returns NBTBase. This now finds NBTBase:createTag(byte). I will see if I can fix this without breaking version independence.
