### ISSUE TITLE
Power nbt wont work for 1.7.10 plz help

### ISSUE THREAD

**Issue by noah1234fgfdgdsgsgf** [DPOH-VAR/PowerNBT#41]
Power nbt wont work for 1.7.10 plz help Sorry to bother you?!?!?!?! :) Hope everybody has a great/amazing nite/day?!?!!?!?!? :) Hope everybody has a great/amazing rest of there nite/day!?!?!?!? :)

**Comment by dpohvar** [comment]
1.7.10 was released 8 years ago O_o

Use the oldest version of PowerNBT.
All versions: https://www.spigotmc.org/resources/powernbt.9098/history
For example, PowerNBT 0.8.4.1 works with Bukkit api v 1.7.10.

![image](https://user-images.githubusercontent.com/1461904/156379361-09bb70e9-513f-47f0-ad13-27e2f42ae8ee.png)

**Comment by noah1234fgfdgdsgsgf** [comment]
It still wont work if i give console acces could you fix it? :)

**Comment by noah1234fgfdgdsgsgf** [comment]
This is my discord?!?!?!?!?! :) tinyturtlel1#4257

**Comment by noah1234fgfdgdsgsgf** [comment]
[04.03 03:22:28] [Multicraft] gingerjanosek@atlanticbb.net ran command: nbt
[04.03 03:22:28] [Server] [INFO] /nbt ... use [Tab] key for help

**Comment by noah1234fgfdgdsgsgf** [comment]
> 1.7.10 was released 8 years ago O_o
> 
> Use the oldest version of PowerNBT. All versions: https://www.spigotmc.org/resources/powernbt.9098/history For example, PowerNBT 0.8.4.1 works with Bukkit api v 1.7.10.
> 
> ![image](https://user-images.githubusercontent.com/1461904/156379361-09bb70e9-513f-47f0-ad13-27e2f42ae8ee.png)

:)
