### ISSUE TITLE
PowerNBT not working with KCauldron

### ISSUE THREAD

**Issue by xJonL** [DPOH-VAR/PowerNBT#9]
KCauldron is the revived project of Cauldron. Whenever I try to use the plugin, it returns an error.
http://i.imgur.com/5iU1fEE.jpg

**Comment by DPOH-VAR** [comment]
PowerNBT not designed for KCauldron.
**v0.8.2 beta** tested with _cauldron-1.7.10-1.1207.01.198-server_
Which version you use?
And where it can be downloaded? (maven, git, etc)

**Comment by xJonL** [comment]
Tested with PowerNBT v0.8.2 beta and v0.8.1.
Using KCauldron-1.7.10-1448.121

**Comment by DPOH-VAR** [comment]
hotfix: http://varscript.ru/artifactory/simple/release/me/dpohvar/powernbt/PowerNBT/0.8.4.1/
